<div class="jumbotron">
  <h1>Find the Right Stack for You</h1>
  <p>People always debate which the best stack. <br>
  The correct answer is: </p>
  <p><strong>There is none. </strong></p>
  <p>The best stack is the one that fits your needs, there is no stack that is best at everything.</p>
</div>

<div class="row">
  <div class="col-md-2"><a href="./Basic_Stack" class="center-block text-center main-btn btn"><h2>Basic Stack</h2></a></div>
  <div class="col-md-2"><a href="./Front-End_Stack" class="center-block text-center main-btn btn"><h2>Front-End Stack</h2></a></div>
  <div class="col-md-2"><a href="./Back-End_Stack" class="center-block text-center main-btn btn"><h2>Back-End Stack</h2></a></div>
  <div class="col-md-2"><a href="./Database_Stack" class="center-block text-center main-btn btn"><h2>Database Stack</h2></a></div>
  <div class="col-md-2"><a href="./Analytics_Stack" class="center-block text-center main-btn btn"><h2>Analytics Stack</h2></a></div>
  <div class="col-md-2"><a href="./Business_Stack" class="center-block text-center main-btn btn"><h2>Business Stack</h2></a></div>
</div>